# Generated by Django 2.1.7 on 2019-03-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='useraddress',
            field=models.CharField(default='Address', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userphone',
            field=models.IntegerField(default=9833, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userstream',
            field=models.CharField(default='Eng', max_length=50),
            preserve_default=False,
        ),
    ]
