# Generated by Django 2.1.7 on 2019-03-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20190319_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userphone',
            field=models.FloatField(unique=True),
        ),
    ]
