# Generated by Django 2.1.7 on 2019-03-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_auto_20190319_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userphone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
